name: Check ticket price and send msg to telegram

# on:
#   schedule:
#     # Runs "every 8 hours" (see https://crontab.guru)
#     #- cron: '0 */8 * * *'
#     - cron: '* * * * *'
on: 
  workflow_dispatch:

jobs:
  run_script:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: ls #pip install -r requirements.txt
      - name: Run script
        run: python3 nz_tickets_job.py