name: Check ticket price and send msg to telegram

on:
  schedule:
    # Runs "every 8 hours" (see https://crontab.guru)
    #- cron: '0 */8 * * *'
    - cron: '* * * * *'
jobs:
  run_script:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python3 nz_tickets_job.py