name: Alert ticket price

on:
  schedule:
    # Runs "every 8 hours" (see https://crontab.guru)
    - cron: '0 */8 * * *'
    #- cron: '* * * * *'

# Manual trigger
# on: 
#   workflow_dispatch:

env:
  CHAT_ID: ${{secrets.CHAT_ID}}
  TELEGRAM_API_KEY: ${{secrets.TELEGRAM_API_KEY}}
  TICKET_URL: ${{secrets.TICKET_URL}}

jobs:
  run_script:
    name: Run script .py script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python3 nz_tickets_job.py